name = "sistema-pos-microbollos"
main = "worker.js"
compatibility_date = "2025-08-18"

[site]
bucket = "./"
entry-point = "worker.js"

[build]
command = "npm run build"
output_dir = "dist"

[env.production]
name = "sistema-pos-microbollos-prod"
route = "pos.microbollos.com/*"
workers_dev = true

[env.development]
name = "sistema-pos-microbollos-dev"
workers_dev = true

[[kv_namespaces]]
binding = "SESSION_STORE"
id = "86794f5e1ad14bb3b8a007ca881e6509"    # ID de producción
preview_id = "86794f5e1ad14bb3b8a007ca881e6509"    # Usamos el mismo ID para preview por ahora

[vars]
ENVIRONMENT = "production"
SESSION_DURATION = "86400"                   # 24 horas en segundos
