# wrangler.toml
name = "sistema-pos-mg"
compatibility_date = "2025-08-14"
pages_build_output_dir = "frontend"

[[d1_databases]]
binding = "DB"
database_name = "sistema-pos-mg"
database_id = "a87247bd-4618-44da-9aaf-9c8874c29805"
