# wrangler.toml
name = "sistema-pos-mg"
compatibility_date = "2025-08-14"

# Configuración de Pages
[build]
command = ""
upload.format = "service-worker"

# Configuración de la base de datos D1
[[d1_databases]]
binding = "DB"
database_name = "sistema-pos-mg"
database_id = "a87247bd-4618-44da-9aaf-9c8874c29805"

# Rutas y bindings
[site]
bucket = "./frontend"
entry-point = "frontend/worker.js"
