# wrangler.toml
name = "sistema-pos-mg"
compatibility_date = "2025-08-14"
main = "frontend/worker.js"

# Configuraci贸n de Pages y Build
[build]
command = "cd frontend && npm install && npm run build"

[site]
bucket = "./frontend"
entry-point = "_worker.js"

# Directorio de salida de la build
pages_build_output_dir = "frontend"

# Configuraci贸n de Functions
[functions]
directory = "frontend/functions"
include = ["api/**/*.js"]
exclude = ["**/*.test.js", "**/*.spec.js"]

# Configuraci贸n de assets
[assets]
include = [
  "frontend/js/**/*",
  "frontend/assets/**/*",
  "frontend/dist/**/*",
  "frontend/index.html",
  "frontend/_worker.js",
  "frontend/_routes.json"
]
exclude = [
  "frontend/functions/**/*",
  "frontend/node_modules/**/*",
  "**/README.md",
  "**/.git/**"
]

# Configuraci贸n de la base de datos D1
[[d1_databases]]
binding = "DB"
database_name = "sistema-pos-mg"
database_id = "a87247bd-4618-44da-9aaf-9c8874c29805"

# Variables de entorno
[env.production]
name = "sistema-pos-mg-prod"
[[env.production.d1_databases]]
binding = "DB"
database_name = "sistema-pos-mg"
database_id = "a87247bd-4618-44da-9aaf-9c8874c29805"

[env.development]
name = "sistema-pos-mg-dev"
